DO $$ BEGIN
 CREATE TYPE "public"."order_status" AS ENUM('PENDIENTE', 'ESPERANDO_PAGO', 'PAGO_RECIBIDO', 'COMPLETADO', 'FALLIDO', 'ENVIADO', 'CANCELADO', 'RECHAZADO', 'REEMBOLSADO', 'DISPUTADO');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "status" "order_status" DEFAULT 'PENDIENTE' NOT NULL;